# Django-learningLog

56862@DESKTOP-PQGKOPT MINGW64 /d/CS/DjangoProject (master)
$ git remote add origin https://github.com/Laurentlsb/Django-Project.git
fatal: remote origin already exists.

56862@DESKTOP-PQGKOPT MINGW64 /d/CS/DjangoProject (master)
$ git push -u origin master
To https://github.com/Laurentlsb/Django-Project.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/Laurentlsb/Django-Project.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

56862@DESKTOP-PQGKOPT MINGW64 /d/CS/DjangoProject (master)
$ ^C

56862@DESKTOP-PQGKOPT MINGW64 /d/CS/DjangoProject (master)
$ Note about fast-forwards' in 'git push --help
bash: Note: command not found

56862@DESKTOP-PQGKOPT MINGW64 /d/CS/DjangoProject (master)
$ git remote add origin https://github.com/Laurentlsb/Django-learningLog.git
fatal: remote origin already exists.

56862@DESKTOP-PQGKOPT MINGW64 /d/CS/DjangoProject (master)
$ git remote add sd https://github.com/Laurentlsb/Django-learningLog.git

56862@DESKTOP-PQGKOPT MINGW64 /d/CS/DjangoProject (master)
$ git push -u sd master
Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 8 threads
Compressing objects: 100% (15/15), done.
Writing objects: 100% (16/16), 9.29 KiB | 1.55 MiB/s, done.
Total 16 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), done.
To https://github.com/Laurentlsb/Django-learningLog.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'sd'.
